optionsClassName: 
optionsClassFullName: 
configurationSamples: []
description: This processor can migrate `test configuration`. This should be run before `LinkMigrationConfig`.
className: TestConfigurationsMigrationProcessor
typeName: Processors
architecture: v1
options: []
status: Beta
processingTarget: Suites & Plans
classFile: /src/MigrationTools.Clients.AzureDevops.ObjectModel/Processors/TestConfigurationsMigrationProcessor.cs
optionsClassFile: 
