optionsClassName: TfsTeamSettingsToolOptions
optionsClassFullName: MigrationTools.Tools.TfsTeamSettingsToolOptions
configurationSamples: []
description: The TfsUserMappingTool is used to map users from the source to the target system. Run it with the ExportUsersForMappingContext to create a mapping file then with WorkItemMigrationContext to use the mapping file to update the users in the target system as you migrate the work items.
className: TfsTeamSettingsTool
typeName: Tools
architecture: v1
options: []
status: missng XML code comments
processingTarget: missng XML code comments
classFile: /src/MigrationTools.Clients.AzureDevops.ObjectModel/Tools/TfsTeamSettingsTool.cs
optionsClassFile: /src/MigrationTools.Clients.AzureDevops.ObjectModel/Tools/TfsTeamSettingsToolOptions.cs
